export const questions = [
    {
        topic: 'DSA',
        text: 'Which data structure uses LIFO order?',
        options: ['Queue', 'Stack', 'Tree', 'Graph'],
        correctAnswer: 'Stack',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'DSA',
        text: 'Which algorithm is used to find the shortest path in a weighted graph?',
        options: ['DFS', 'BFS', "Dijkstra's", "Kruskal's"],
        correctAnswer: "Dijkstra's",
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'DSA',
        text: 'What is the average-case time complexity of binary search?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
        correctAnswer: 'O(log n)',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'DSA',
        text: 'Which traversal visits the root node between the left and right subtree?',
        options: ['Preorder', 'Postorder', 'Inorder', 'Level order'],
        correctAnswer: 'Inorder',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'DSA',
        text: 'Which data structure is typically used to implement recursion internally?',
        options: ['Queue', 'Heap', 'Stack', 'Hash table'],
        correctAnswer: 'Stack',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'OOP',
        text: 'Which concept allows a class to have multiple methods with the same name but different parameters?',
        options: ['Encapsulation', 'Inheritance', 'Method Overriding', 'Method Overloading'],
        correctAnswer: 'Method Overloading',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'OOP',
        text: 'Which OOP principle hides internal implementation details from the user?',
        options: ['Polymorphism', 'Inheritance', 'Encapsulation', 'Association'],
        correctAnswer: 'Encapsulation',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'OOP',
        text: 'What is it called when a child class provides its own implementation of a parent method?',
        options: ['Overloading', 'Abstraction', 'Overriding', 'Composition'],
        correctAnswer: 'Overriding',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'OOP',
        text: 'Which keyword is commonly used to create a class that cannot be instantiated?',
        options: ['virtual', 'abstract', 'static', 'private'],
        correctAnswer: 'abstract',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'OOP',
        text: 'Which relationship describes one class using another class as a field or member?',
        options: ['Inheritance', 'Composition', 'Polymorphism', 'Overloading'],
        correctAnswer: 'Composition',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'DBMS',
        text: 'Which SQL statement is used to extract data from a database?',
        options: ['GET', 'EXTRACT', 'OPEN', 'SELECT'],
        correctAnswer: 'SELECT',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'DBMS',
        text: 'Which normal form removes partial dependency from a table?',
        options: ['1NF', '2NF', '3NF', 'BCNF'],
        correctAnswer: '2NF',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'DBMS',
        text: 'Which type of key uniquely identifies each row in a table?',
        options: ['Foreign key', 'Composite key', 'Primary key', 'Candidate key'],
        correctAnswer: 'Primary key',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'DBMS',
        text: 'What does ACID stand for in database transactions?',
        options: ['Atomicity, Consistency, Isolation, Durability', 'Accuracy, Control, Integrity, Data', 'Access, Consistency, Indexing, Durability', 'Atomicity, Clarity, Isolation, Distribution'],
        correctAnswer: 'Atomicity, Consistency, Isolation, Durability',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'DBMS',
        text: 'Which JOIN returns only rows that have matching values in both tables?',
        options: ['LEFT JOIN', 'RIGHT JOIN', 'FULL JOIN', 'INNER JOIN'],
        correctAnswer: 'INNER JOIN',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'System Design',
        text: 'What technique distributes traffic across multiple servers?',
        options: ['Caching', 'Database Indexing', 'Load Balancing', 'Sharding'],
        correctAnswer: 'Load Balancing',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'System Design',
        text: 'Which component is commonly used to reduce database load by serving repeated reads quickly?',
        options: ['Cache', 'Message queue', 'Proxy server', 'Firewall'],
        correctAnswer: 'Cache',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'System Design',
        text: 'What is sharding primarily used for?',
        options: ['Encrypting traffic', 'Splitting data across multiple databases', 'Balancing CPU load inside one server', 'Compressing images'],
        correctAnswer: 'Splitting data across multiple databases',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'System Design',
        text: 'Which system component is best suited for asynchronous task processing?',
        options: ['Message queue', 'CDN', 'Load balancer', 'SQL view'],
        correctAnswer: 'Message queue',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'System Design',
        text: 'Which metric tells you how long a service takes to respond to a request?',
        options: ['Latency', 'Throughput', 'Availability', 'Bandwidth'],
        correctAnswer: 'Latency',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'HR',
        text: 'What is the best approach when answering Tell me about yourself in an interview?',
        options: ['Share unrelated personal history', 'Give a concise professional summary', 'Read your full resume word for word', 'Talk only about hobbies'],
        correctAnswer: 'Give a concise professional summary',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'HR',
        text: 'How should you answer a question about a conflict with a teammate?',
        options: ['Blame the teammate directly', 'Avoid the question completely', 'Explain the situation, action, and resolution professionally', 'Say conflicts never happen'],
        correctAnswer: 'Explain the situation, action, and resolution professionally',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'HR',
        text: 'What is a strong way to answer Why do you want to work here?',
        options: ['Because I need any job', 'Because the office looks nice', 'Because the role and company align with your goals and skills', 'Because my friend told me to apply'],
        correctAnswer: 'Because the role and company align with your goals and skills',
        difficulty: 'Easy',
        timeLimit: 10,
    },
    {
        topic: 'HR',
        text: 'What should you emphasize when discussing a past failure?',
        options: ["How it was someone else's fault", 'What you learned and how you improved', 'Why it was not important', 'Why the interviewer should ignore it'],
        correctAnswer: 'What you learned and how you improved',
        difficulty: 'Medium',
        timeLimit: 10,
    },
    {
        topic: 'HR',
        text: 'What is usually the best response to Do you have any questions for us?',
        options: ['Say no immediately', 'Ask thoughtful questions about the role or team', 'Ask only about vacation days', 'Change the subject'],
        correctAnswer: 'Ask thoughtful questions about the role or team',
        difficulty: 'Easy',
        timeLimit: 10,
    },
];
